@port={{$dotenv PORT}}
@host=http://localhost:{{port}}

### GET /test

POST {{host}}/login

### POST /test

POST {{host}}/login
Content-Type: application/json

{
    "promo": "Nemo",
    "saison": 6,
    "au_taquet": true
}

###

PATCH {{host}}/test

###

DELETE {{host}}/test